name: Build image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build image
      run: docker build -t app-devops:latest .